### ISSUE TITLE
install without gui?

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/ms2rescore#59]
Hello,
I used to be able to install without issues and now there are various failures because of wxPython and/or gooey. I need to be able to install without ui on virtual machines (i.e. docker) and on HPCs. Do you have instructions for doing that? 
I tried removing the requirement for gooey but it doesn't seem to work... (tried removing gui.py and the reference to gooey in setup.py before `python setup.py install`)
Thanks!

**Comment by RalfG** [comment]
Hi Sebastien,

I suspect the issue is the new gooey-based GUI in DeepLC [(v1.1.1)](https://github.com/compomics/DeepLC/releases/tag/v1.1.1). I just released a new DeepLC version ([v1.1.2)](https://github.com/compomics/DeepLC/releases/tag/v1.1.2) where gooey is an optional dependency (as is the case for MS²Rescore itself). The install should now work again as expected.

Best,
Ralf

**Comment by Seb-Leb** [comment]
It works! great, thank you!
