### ISSUE TITLE
Issue in selecting the mgf file of the spectrum file in GUI

### ISSUE THREAD

**Issue by eunice1029** [compomics/ms2rescore#85]
Hi, I've got a quick question about selecting the mgf file in the Spectrum file directory. 

I'm currently using GUI by running [python -m ms2rescore.gui] in the command window and I got a window where I could browse files and folders directly. I tried putting in my mgf spectrum files but when I click the browse button, and try to select the file, it gives me a message, "No items match your search."
And when I select the folder and try running, I get an error, "FileNotFoundError: [WinError 2] The system cannot find the file specified."

I am wondering why I'm not able to see and select my files in the Spectrum file directory browse.

Thank you so much.

**Comment by RalfG** [comment]
Hi @eunice1029 ,

If you are still interested, I recommend trying out the new beta version of MS²Rescore 3.0. It has a completely rebuilt desktop application and a much simpler installation process. This issue should also be fixed in the new version.

https://github.com/compomics/ms2rescore/releases/tag/v3.0.0b4

Let us know if you do run into any other issues.

Best,
Ralf
